const express = require('express');
const router = express.Router();
const { requireAdmin } = require('../middleware/auth');
const { validateQuery, schemas } = require('../middleware/validation');
const adminController = require('../controllers/adminController');
router.use(requireAdmin);
router.get('/stats', adminController.getStats);
router.get('/auctions', validateQuery(schemas.adminAuctionPagination), adminController.getAllAuctions);
router.post('/auctions/:id/start', adminController.startAuction);
router.post('/auctions/:id/end', adminController.endAuction);
router.post('/auctions/:id/reset', adminController.resetAuction);
router.put('/auctions/:id', adminController.updateAuction);
router.delete('/auctions/:id', adminController.deleteAuction);
router.get('/users', validateQuery(schemas.adminUserPagination), adminController.getAllUsers);
router.get('/users/:id', adminController.getUserById);
router.put('/users/:id', adminController.updateUser);
router.delete('/users/:id', adminController.deleteUser);
router.get('/monitoring', adminController.getSystemStatus);
router.get('/monitoring/activity', adminController.getRecentActivity);
router.get('/invoices', validateQuery(schemas.adminPagination), adminController.getAllInvoices);
router.get('/invoices/:id', adminController.getInvoiceById);
router.get('/invoices/:id/download', adminController.downloadInvoice);
router.get('/emails', validateQuery(schemas.adminPagination), adminController.getAllEmails);
router.get('/emails/:id', adminController.getEmailById);
router.post('/emails/resend', adminController.resendEmail);
module.exports = router;
